interface HanziRow {
    id: number,
    simplified: string,
    traditional: string,
    pinyin: string,
    douyinzi: string,
    radical: string,
    simplifiedStrokeCount: string,
    traditionalStrokeCount: string,
    definition: string,
    about: string,
    hskLevel: number, 
    characterCount: number, 
    category: string,
    frequency: string,
    commonWords: string,
    sentences: string,
}